items:
  - 267,1,0,DURABILITY:10
  - 261,1,0,ARROW_INFINITE:1
  - 320,9,0
  - 346,1,0
  - 322,5,0
  - 262,1,0
  - 310,1,0,PROTECTION_ENVIRONMENTAL:1
  - 312,1,0,PROTECTION_ENVIRONMENTAL:1
  - 307,1,0,PROTECTION_ENVIRONMENTAL:1
  - 309,1,0,PROTECTION_ENVIRONMENTAL:1